mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
]

mysite/todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_task, name='add_task'),
    path('export/csv/', views.export_users_csv, name='export_users_csv'),
    path('export/xlsx/', views.export_users_xlsx, name='export_users_xlsx'),
    path('delete/', views.delete_task, name='delete_task'),
]

mysite/todo/models.py
import datetime

from django.db import models
from django.utils import timezone


class Task(models.Model):
    task_name=models.CharField(max_length=200)
    description=models.CharField(max_length=500)

    def __str__(self):
        return self.task_name


# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date = models.DateTimeField('date published')
#
#     def __str__(self):
#         return self.question_text
#
#     def was_published_recently(self):
#         now = timezone.now()
#         return now - datetime.timedelta(days=1) <= self.pub_date <= now
#
# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)
#
#     def __str__(self):
#         return self.choice_text

mysite/todo/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
import xlwt

from .models import Task
import csv


def index(request):

    tasks = Task.objects.all()
    context = {
        'task_list' : tasks,
    }
    return render(request,'todo/index.html',context)

def add_task(request):
    t = Task(task_name=request.POST['task'],description=request.POST['description'])
    t.save()
    # return HttpResponse("done")
    return HttpResponseRedirect(reverse('todo:index'))

def export_users_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="users.csv"'
    writer = csv.writer(response)

    tasks = Task.objects.all().values_list('task_name','description')
    for task in tasks:
        # writer.writerow([task.task_name])
        writer.writerow(task)

    # users = User.objects.all().values_list('username', 'first_name', 'last_name', 'email')
    # for user in users:
    #     writer.writerow(user)

    return response
    return HttpResponseRedirect(reverse('todo:index'))

def export_users_xlsx(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="users.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Tasks')

    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Task', 'Description']

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    font_style = xlwt.XFStyle()

    rows = Task.objects.all().values_list('task_name','description')
    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)
    return response
    return HttpResponseRedirect(reverse('todo:index'))

def delete_task(request):
    t=Task.objects.filter(task_name=request.POST['task_name'])
    t.delete()
    return HttpResponseRedirect(reverse('todo:index'))








# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})
#
# def detail(request,question_id):
#
#     question = get_object_or_404(Question,pk = question_id)
#     return render(request,'polls/detail.html',{'question':question})

mysite/todo/templates/todo/index.html
<html><!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'todo/style.css' %}">

  </head>

<body>

<div id="wrapper">
    <h1 id="heading">TODO LIST</h1>
    <h5 id="subheading">A list for important tasks</h5>
    <form action="{% url 'todo:add_task' %}" method="post">
        {% csrf_token %}
        <input type="text" name="task" id="text-box" placeholder="Enter a New Task.."></input>
        <input type="text" name="description" id="text-box" placeholder="Enter a description.."></input>
   <input type="submit" id="submit" value="Add Task">
    </form>


<a href="{% url 'todo:export_users_csv' %}">
    <button id="download">Export to CSV</button>
</a>

    <a href="{% url 'todo:export_users_xlsx' %}">
    <button id="download">Export to Excel</button>
</a>

<table>
    <tr>
        <th>Task</th>
        <th>Sub-task</th>
        <th>Delete</th>
    </tr>
{% if task_list %}
    {% for task in task_list %}
    <tr>
        <td>{{ task.task_name }}</td>
        <td>{{ task.description }}</td>
        <td>
        <form action="{% url 'todo:delete_task' %}" method="post">
            {% csrf_token %}
            <input type="text" name="task_name" value="{{task.task_name}}" style="display:none"></input>
            <input type="submit" value="X">
        </form>
        </td>
    </tr>
    {% endfor %}

{% else %}
    <p>No task available</p>
{% endif %}
</table>

</div>
</body>

<script>
    console.log('yes');

</script>



</html>